### ISSUE TITLE
Typo in Hero Banner on Home Page

### ISSUE THREAD

**Issue by damen-dotcms** [damen-dotcms/issue-test#5]
[![Screenshot_2022-10-27_06-31-04.png](https://mrkr.io/s/635a25a84761a093e5ff147f/2)](https://mrkr.io/s/635a25a84761a093e5ff147f/0)

Should say "Management"

---

**Reported by:** Damen Gilland (damen.gilland@dotcms.com)

**Source URL:** [https://www.dotcms.com/](https://www.dotcms.com/)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/635a25a84761a093e5ff1483_4d000fe4e02af677?advanced=1)

**Console:** [📃  0 logs](https://app.marker.io/i/635a25a84761a093e5ff1483_4d000fe4e02af677?advanced=1&activePane=console)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Firefox 106.0</td></tr><tr><td><strong>Screen Size</strong></td><td>2056 x 1329</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15</td></tr><tr><td><strong>Viewport Size</strong></td><td>2056 x 950</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by damen-dotcms** [comment]
This is NOT a real screenshot. (=

**Comment by Melissa-dotCMS** [comment]
This issue is already fixed.
